---
- name: Deploy Web App                                  # This is the name of the playbook
  hosts: web                                           # The group of hosts in the inventory file where the tasks will be executed
  become: true                                           # Use privilege escalation (e.g., sudo) for tasks requiring elevated permissions
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Download Docker GPG key
      ansible.builtin.shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      become: yes

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      become: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes
      become: yes

    - name: Set Docker Compose URL
      ansible.builtin.set_fact:
        docker_compose_url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"

    - name: Install Docker Compose
      ansible.builtin.command: >
        curl -L "{{ docker_compose_url }}"
        -o /usr/local/bin/docker-compose
      become: yes

    - name: Apply executable permissions to Docker Compose binary
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        mode: '0755'
      become: yes
